//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PST.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WDSResponse
    {
        public System.Guid Id { get; set; }
        public string Sub_Family { get; set; }
        public string Series { get; set; }
        public string Brand_name { get; set; }
        public string T_R { get; set; }
        public string PM { get; set; }
        public string Category { get; set; }
        public string KUBUN { get; set; }
        public string Area { get; set; }
        public string Supply_Route { get; set; }
        public string EURO_Country { get; set; }
        public string GSKU { get; set; }
        public string G_Frame { get; set; }
        public string PNO { get; set; }
        public string Ship_Style { get; set; }
        public string InHouse_ODM { get; set; }
        public string Prod { get; set; }
        public string FCS_date { get; set; }
        public string Customer { get; set; }
        public string Status { get; set; }
        public string Cut_off { get; set; }
        public Nullable<System.DateTime> Cut_off_date { get; set; }
        public string Month { get; set; }
        public string Week { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Sales_Demand_Previous { get; set; }
        public Nullable<double> Sales_Demand_Current_a_ { get; set; }
        public Nullable<double> HQ_Original_Previous { get; set; }
        public Nullable<double> HQ_Original_Current_g_ { get; set; }
        public Nullable<double> HQ_Forecast_Previous { get; set; }
        public Nullable<double> PSI_0506__b_ { get; set; }
        public Nullable<double> CP_Simulation_Previous { get; set; }
        public Nullable<double> CP_Simulation_Current { get; set; }
        public Nullable<double> HQ_Simulation_Previous { get; set; }
        public Nullable<double> HQ_Simulation_Current { get; set; }
        public Nullable<double> Sales_Response_Previous_e_ { get; set; }
        public Nullable<double> Sales_Response_Current_f_ { get; set; }
        public Nullable<double> Pullin_Response_Previous { get; set; }
        public Nullable<double> Pullin_Response_Current { get; set; }
        public Nullable<double> MFG_Response_Previous_c_ { get; set; }
        public Nullable<double> WDS_Response_0509__d_ { get; set; }
        public Nullable<double> d_a { get; set; }
        public Nullable<double> d_b { get; set; }
        public Nullable<double> d_c { get; set; }
        public Nullable<double> f_e { get; set; }
        public Nullable<double> f_g { get; set; }
        public string Segment { get; set; }
        public string CPU { get; set; }
        public string LCD { get; set; }
        public string HDD { get; set; }
        public string Communication { get; set; }
        public string Mini_PCI { get; set; }
        public string Bluetooth { get; set; }
        public string Battery { get; set; }
        public string OS { get; set; }
        public string Pointing_Device { get; set; }
        public string Graphics_Controller { get; set; }
        public string Indent { get; set; }
        public string Recovery { get; set; }
        public string ODD { get; set; }
        public string Speaker { get; set; }
        public string TV_tuner { get; set; }
        public string Warranty { get; set; }
        public string Remote_Control { get; set; }
        public string Office { get; set; }
        public string KeyBoard { get; set; }
        public string OS_Language { get; set; }
        public string Warranty_Extension_ { get; set; }
        public string RecycleLabel { get; set; }
        public string DVD_Region_Code { get; set; }
        public string Energy_Star_Label { get; set; }
        public string RecoveryCD { get; set; }
        public string Memory_Slot1 { get; set; }
        public string Memory_Slot2 { get; set; }
        public string AC_Cable { get; set; }
        public string C2nd_HDD { get; set; }
        public string LAN { get; set; }
        public string Button { get; set; }
        public string Recovery_HDD { get; set; }
        public string Recovery_Media { get; set; }
        public string OnSite_Service { get; set; }
        public string Color_Variation { get; set; }
        public string Mouse { get; set; }
        public string Security { get; set; }
        public string Generation { get; set; }
        public string C3G { get; set; }
        public string C2nd_TV_Tuner { get; set; }
        public string Windows_Sticker { get; set; }
        public string Connector { get; set; }
        public string Web_Camera_Mic { get; set; }
        public string Disk_Cache { get; set; }
        public string Card_Slot { get; set; }
        public string KeyBoard_Color { get; set; }
        public string Target_Customer { get; set; }
        public string Pen_Device { get; set; }
        public string OS_Category { get; set; }
        public string Backend_Processor { get; set; }
        public string Anti_Virus_SW { get; set; }
        public string Energy_Star_Label_ODM_ { get; set; }
        public string Micro_SATA_SSD_for_Dedicated_SSD_Slot { get; set; }
        public string Flush_Screen { get; set; }
        public string Ambient_Sensor { get; set; }
        public string PCBA_BTO_Combination { get; set; }
        public string External_IR_Transceiver { get; set; }
        public string KeyBoard_BTO_Combination { get; set; }
        public string Discrete_Graphics_Controller { get; set; }
        public string Chipset { get; set; }
        public string Wireless_Device { get; set; }
        public string Memory_Slot3 { get; set; }
        public string Brand_No { get; set; }
        public string Product_Category { get; set; }
        public string Importer { get; set; }
        public string Special_Bundle { get; set; }
        public string Wireless_Display { get; set; }
        public string LTE { get; set; }
        public string Dock { get; set; }
        public string MAC_address_sticker { get; set; }
        public string Web_Camera_Mic_Back_ { get; set; }
        public string Memory_Slot4 { get; set; }
        public string AC_Plug_Type { get; set; }
        public string Carry_Case { get; set; }
        public string Package { get; set; }
        public string SmallParts { get; set; }
        public string MFGInfo { get; set; }
        public string Antenna { get; set; }
        public string Keyboard_TAIS { get; set; }
        public string Warranty_ODM_ { get; set; }
        public string Recovery_CD_ODM_ { get; set; }
        public string LAN_ODM_ { get; set; }
        public string PackageL { get; set; }
        public string AC_Adaptor { get; set; }
        public string RatingLabel { get; set; }
        public string Remote_Control_STC_ { get; set; }
        public string Remote_Control_TAIS { get; set; }
        public string PCB { get; set; }
        public string Country_Pack { get; set; }
        public string KeyBoard_Dock { get; set; }
        public string MediaBridgeSlot { get; set; }
        public string Indent1 { get; set; }
        public string Indent2 { get; set; }
        public string Security_Frame { get; set; }
        public string Security_PCBA { get; set; }
        public string Security_FP { get; set; }
        public string KeyBoard_FP { get; set; }
        public int FFPSetId { get; set; }
        public int Seq { get; set; }
    
        public virtual FFPSet FFPSet { get; set; }
    }
}
