//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PST.UI.Common.FFPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FFPService.IFFPService")]
    public interface IFFPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPService/Add", ReplyAction="http://tempuri.org/IFFPService/AddResponse")]
        PST.Domain.Response<System.Guid> Add(PST.Domain.FFP item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPService/Add", ReplyAction="http://tempuri.org/IFFPService/AddResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response<System.Guid>> AddAsync(PST.Domain.FFP item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPService/AddFfp", ReplyAction="http://tempuri.org/IFFPService/AddFfpResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PST.Domain.Response<System.Guid>))]
        PST.Domain.Response AddFfp(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPService/AddFfp", ReplyAction="http://tempuri.org/IFFPService/AddFfpResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response> AddFfpAsync(string sql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFFPServiceChannel : PST.UI.Common.FFPService.IFFPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FFPServiceClient : System.ServiceModel.ClientBase<PST.UI.Common.FFPService.IFFPService>, PST.UI.Common.FFPService.IFFPService {
        
        public FFPServiceClient() {
        }
        
        public FFPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FFPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PST.Domain.Response<System.Guid> Add(PST.Domain.FFP item) {
            return base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response<System.Guid>> AddAsync(PST.Domain.FFP item) {
            return base.Channel.AddAsync(item);
        }
        
        public PST.Domain.Response AddFfp(string sql) {
            return base.Channel.AddFfp(sql);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response> AddFfpAsync(string sql) {
            return base.Channel.AddFfpAsync(sql);
        }
    }
}
