//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PST.UI.Common.FFPSetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FFPSetService.IFFPSetService")]
    public interface IFFPSetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPSetService/HasData", ReplyAction="http://tempuri.org/IFFPSetService/HasDataResponse")]
        PST.Domain.Response<bool> HasData(string setName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPSetService/HasData", ReplyAction="http://tempuri.org/IFFPSetService/HasDataResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response<bool>> HasDataAsync(string setName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPSetService/Upsert", ReplyAction="http://tempuri.org/IFFPSetService/UpsertResponse")]
        PST.Domain.Response<int> Upsert(string setName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFFPSetService/Upsert", ReplyAction="http://tempuri.org/IFFPSetService/UpsertResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response<int>> UpsertAsync(string setName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFFPSetServiceChannel : PST.UI.Common.FFPSetService.IFFPSetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FFPSetServiceClient : System.ServiceModel.ClientBase<PST.UI.Common.FFPSetService.IFFPSetService>, PST.UI.Common.FFPSetService.IFFPSetService {
        
        public FFPSetServiceClient() {
        }
        
        public FFPSetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FFPSetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFPSetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FFPSetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PST.Domain.Response<bool> HasData(string setName) {
            return base.Channel.HasData(setName);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response<bool>> HasDataAsync(string setName) {
            return base.Channel.HasDataAsync(setName);
        }
        
        public PST.Domain.Response<int> Upsert(string setName) {
            return base.Channel.Upsert(setName);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response<int>> UpsertAsync(string setName) {
            return base.Channel.UpsertAsync(setName);
        }
    }
}
