//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PST.UI.Common.WDResponseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WDResponseService.IWDResponseService")]
    public interface IWDResponseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWDResponseService/AddItems", ReplyAction="http://tempuri.org/IWDResponseService/AddItemsResponse")]
        PST.Domain.Response AddItems(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWDResponseService/AddItems", ReplyAction="http://tempuri.org/IWDResponseService/AddItemsResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response> AddItemsAsync(string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWDResponseService/RemoveBySetId", ReplyAction="http://tempuri.org/IWDResponseService/RemoveBySetIdResponse")]
        PST.Domain.Response RemoveBySetId(int setId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWDResponseService/RemoveBySetId", ReplyAction="http://tempuri.org/IWDResponseService/RemoveBySetIdResponse")]
        System.Threading.Tasks.Task<PST.Domain.Response> RemoveBySetIdAsync(int setId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWDResponseServiceChannel : PST.UI.Common.WDResponseService.IWDResponseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WDResponseServiceClient : System.ServiceModel.ClientBase<PST.UI.Common.WDResponseService.IWDResponseService>, PST.UI.Common.WDResponseService.IWDResponseService {
        
        public WDResponseServiceClient() {
        }
        
        public WDResponseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WDResponseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WDResponseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WDResponseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PST.Domain.Response AddItems(string sql) {
            return base.Channel.AddItems(sql);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response> AddItemsAsync(string sql) {
            return base.Channel.AddItemsAsync(sql);
        }
        
        public PST.Domain.Response RemoveBySetId(int setId) {
            return base.Channel.RemoveBySetId(setId);
        }
        
        public System.Threading.Tasks.Task<PST.Domain.Response> RemoveBySetIdAsync(int setId) {
            return base.Channel.RemoveBySetIdAsync(setId);
        }
    }
}
